window.EVENTS = [
  {
    "id": "cuban-missile-crisis",
    "year": "October 1962",
    "location": "CUBA · UNITED STATES · SOVIET UNION",
    "category": "Nuclear brinkmanship",
    "scope": "Global threat",
    "title": "Cuban Missile Crisis",
    "deck": "Soviet missiles in Cuba brought two nuclear superpowers into a direct confrontation.",
    "what": "After U-2 photographs revealed missile sites, Kennedy announced a naval quarantine. An invasion, an air strike, or a clash at sea could have widened the crisis into nuclear war.",
    "outcome": "Khrushchev agreed to remove the missiles. Washington pledged not to invade Cuba and privately agreed to withdraw its Jupiter missiles from Turkey.",
    "nuance": "A genuine global close call. No reliable percentage can tell us how likely nuclear war actually was.",
    "source": "https://en.wikipedia.org/wiki/Cuban_Missile_Crisis"
  },
  {
    "id": "b59",
    "year": "27 October 1962",
    "location": "CARIBBEAN SEA · NEAR CUBA",
    "category": "Nuclear close call",
    "scope": "Global escalation risk",
    "title": "Soviet submarine B-59",
    "deck": "A Soviet submarine carried a nuclear torpedo into the most dangerous days of the Cuban crisis.",
    "what": "U.S. ships dropped signaling depth charges near B-59. Cut off from clear information, its crew faced heat, exhaustion, and uncertainty about whether war had begun.",
    "outcome": "Accounts describe Vasili Arkhipov opposing a nuclear launch. The submarine surfaced without firing its nuclear weapon.",
    "nuance": "Part of the Cuban Missile Crisis, but a distinct incident. Details of the deliberations come from later accounts and are debated.",
    "source": "https://en.wikipedia.org/wiki/Soviet_submarine_B-59"
  },
  {
    "id": "petrov",
    "year": "26 September 1983",
    "location": "SERPUKHOV-15 · SOVIET UNION",
    "category": "False alarm",
    "scope": "Global escalation risk",
    "title": "Soviet early-warning false alarm",
    "deck": "An early-warning system reported an American nuclear attack. Stanislav Petrov judged the alert false.",
    "what": "Soviet satellites appeared to detect a handful of incoming missiles. Petrov doubted that a real first strike would be so small; the warning was later linked to sunlight reflected from clouds.",
    "outcome": "He reported a false alarm rather than a confirmed attack. No nuclear retaliation followed.",
    "nuance": "Petrov did not personally control a launch button. His judgment was one important safeguard within a larger command system.",
    "source": "https://www.chathamhouse.org/2022/03/uncertainty-and-complexity-nuclear-decision-making/05-nuclear-decision-making-case-studies"
  },
  {
    "id": "able-archer",
    "year": "November 1983",
    "location": "EUROPE · NATO & WARSAW PACT",
    "category": "Nuclear brinkmanship",
    "scope": "Global escalation risk",
    "title": "Able Archer 83",
    "deck": "A NATO exercise rehearsing nuclear escalation unfolded during an exceptionally tense Cold War autumn.",
    "what": "Soviet leaders feared a surprise attack disguised as an exercise. Able Archer's procedures helped intensify that suspicion, and some Soviet forces increased their readiness.",
    "outcome": "The exercise ended without a military confrontation. Later disclosures revealed how differently the two sides had read the same events.",
    "nuance": "The scale of Soviet alarm, and just how close war came, remain subjects of historical debate.",
    "source": "https://ahf.nuclearmuseum.org/ahf/history/nuclear-close-calls-able-archer-83/"
  },
  {
    "id": "norwegian-rocket",
    "year": "25 January 1995",
    "location": "NORWAY · RUSSIA",
    "category": "False alarm",
    "scope": "Global escalation risk",
    "title": "Norwegian rocket incident",
    "deck": "A research rocket studying the aurora triggered alarm in Russia's missile-warning system.",
    "what": "The Black Brant XII launch resembled a possible missile threat on radar. Advance scientific notifications had not prevented the alert from reaching the highest levels.",
    "outcome": "Russian officials assessed the trajectory and determined that it posed no threat. No nuclear weapon was launched.",
    "nuance": "The Cold War had ended. The risk of misreading a harmless launch had not.",
    "source": "https://ahf.nuclearmuseum.org/ahf/history/nuclear-close-calls-norwegian-rocket-incident/"
  },
  {
    "id": "norad-1979",
    "year": "9 November 1979",
    "location": "CHEYENNE MOUNTAIN · UNITED STATES",
    "category": "False alarm",
    "scope": "Global escalation risk",
    "title": "NORAD training-tape false alarm",
    "deck": "A training scenario entered the live American warning system and appeared to announce a Soviet attack.",
    "what": "Command centers received a false missile warning, prompting precautionary military actions. Independent radar and satellite information did not show an actual launch.",
    "outcome": "Cross-checks exposed the error before any retaliation. The incident led to efforts to separate exercise data from operational warnings.",
    "nuance": "Warning-system failures are documented; dramatic claims about an exact number of seconds from war are less secure.",
    "source": "https://nsarchive.gwu.edu/briefing-book/nuclear-vault/2020-03-16/false-warnings-soviet-missile-attacks-during-1979-80-led-alert-actions-us-strategic-forces"
  },
  {
    "id": "norad-1980",
    "year": "June 1980",
    "location": "UNITED STATES · STRATEGIC COMMAND CENTERS",
    "category": "False alarm",
    "scope": "Global escalation risk",
    "title": "NORAD computer failure",
    "deck": "Faulty electronics produced false indications of incoming missiles in U.S. warning displays.",
    "what": "Erroneous numbers appeared in messages sent to command centers. The apparent attack triggered alert actions, although other sensors offered no confirmation.",
    "outcome": "Investigators traced the problem to a failed component. Independent evidence helped stop a false warning from becoming a military response.",
    "nuance": "A separate equipment failure from the 1979 training-data incident. Neither caused a nuclear launch.",
    "source": "https://nsarchive.gwu.edu/briefing-book/nuclear-vault/2020-03-16/false-warnings-soviet-missile-attacks-during-1979-80-led-alert-actions-us-strategic-forces"
  },
  {
    "id": "korean-war",
    "year": "1950–1953",
    "location": "KOREAN PENINSULA",
    "category": "War & escalation",
    "scope": "Regional devastation",
    "title": "Korean War",
    "deck": "The Korean War devastated a peninsula while American leaders considered the use of atomic weapons.",
    "what": "U.S.-led UN forces fought North Korean and Chinese forces in a conflict that killed millions. Nuclear options were discussed, raising the prospect of a wider war.",
    "outcome": "No atomic bombs were used. An armistice halted the fighting in 1953, leaving Korea divided.",
    "nuance": "Nuclear escalation was a risk, not a confirmed imminent launch. The catastrophe experienced by Koreans was already real.",
    "source": "https://en.wikipedia.org/wiki/Korean_War"
  },
  {
    "id": "berlin",
    "year": "October 1961",
    "location": "CHECKPOINT CHARLIE · BERLIN",
    "category": "Nuclear brinkmanship",
    "scope": "Global escalation risk",
    "title": "Checkpoint Charlie standoff",
    "deck": "American and Soviet tanks faced each other at a checkpoint in divided Berlin.",
    "what": "A dispute over access rights escalated into an armed confrontation. Loaded tanks stood only a short distance apart, making a local mistake potentially consequential for both superpowers.",
    "outcome": "Back-channel communication helped arrange a gradual withdrawal of the tanks. Neither side opened fire.",
    "nuance": "A dangerous superpower standoff, not evidence that a nuclear launch had been ordered.",
    "source": "https://en.wikipedia.org/wiki/Berlin_Crisis_of_1961"
  },
  {
    "id": "kargil",
    "year": "1999",
    "location": "KARGIL · KASHMIR",
    "category": "War & escalation",
    "scope": "Regional nuclear risk",
    "title": "Kargil War",
    "deck": "India and Pakistan fought in the mountains one year after both conducted nuclear tests.",
    "what": "Pakistani forces crossed the Line of Control, and India fought to retake the positions. The conflict raised international fears that a limited war might expand between nuclear-armed neighbors.",
    "outcome": "Indian military pressure and international diplomacy were followed by Pakistani withdrawal. The war ended without nuclear use.",
    "nuance": "Claims about nuclear readiness during Kargil are contested. This was a regional escalation risk, not a demonstrated near-extinction event.",
    "source": "https://en.wikipedia.org/wiki/Kargil_War"
  },
  {
    "id": "black-death",
    "year": "1346–1353",
    "location": "EURASIA · NORTH AFRICA",
    "category": "Pandemic",
    "scope": "Continental catastrophe",
    "title": "Black Death",
    "deck": "The Black Death tore through communities, killing an enormous share of Europe's population.",
    "what": "Plague spread along connected trade routes. Households, farms, and towns suffered devastating losses; estimates commonly place European mortality at roughly one-third to one-half.",
    "outcome": "The first wave subsided, but outbreaks returned for centuries. Survivors rebuilt in societies reshaped by labor shortages and profound social disruption.",
    "nuance": "It devastated regions across continents. It did not bring all humanity to the edge of extinction.",
    "source": "https://www.ncbi.nlm.nih.gov/books/NBK525302/table/pt5.ch17.sec3.table1/"
  },
  {
    "id": "justinian",
    "year": "541–549 CE",
    "location": "MEDITERRANEAN · EASTERN ROMAN EMPIRE",
    "category": "Pandemic",
    "scope": "Regional catastrophe",
    "title": "Plague of Justinian",
    "deck": "A major plague outbreak struck the Mediterranean world during the reign of Justinian.",
    "what": "The disease reached Constantinople in 542. Contemporary accounts described immense suffering, and genetic evidence has identified the plague bacterium in victims from the wider pandemic.",
    "outcome": "The Eastern Roman Empire survived. Plague continued to recur, alongside wars and other pressures on communities and government.",
    "nuance": "The death toll and long-term economic impact are disputed. Sweeping claims that plague alone caused imperial collapse go beyond the evidence.",
    "source": "https://origins.osu.edu/connecting-history/covid-justinianic-plague-lessons?language_content_entity=en"
  },
  {
    "id": "influenza-1918",
    "year": "1918–1920",
    "location": "WORLDWIDE",
    "category": "Pandemic",
    "scope": "Global catastrophe",
    "title": "Influenza pandemic",
    "deck": "Influenza swept through a world already exhausted by the First World War.",
    "what": "Military movement and crowded living conditions helped the virus spread. Tens of millions died worldwide, and many communities struggled to provide even basic care.",
    "outcome": "Successive waves diminished as immunity and the virus's circulation changed. The suffering outlasted the war that had helped carry it.",
    "nuance": "Global mortality estimates vary widely. This was a vast human disaster, not a near-extinction of the species.",
    "source": "https://en.wikipedia.org/wiki/Spanish_flu"
  },
  {
    "id": "smallpox-americas",
    "year": "1520–1521",
    "location": "CENTRAL MEXICO · MESOAMERICA",
    "category": "Epidemic & conquest",
    "scope": "Regional catastrophe",
    "title": "Smallpox in the Americas",
    "deck": "Smallpox struck the Mexica capital and surrounding communities during the Spanish invasion.",
    "what": "People without prior exposure to the disease faced a deadly epidemic. It intensified a crisis already driven by warfare, siege, alliances, and colonial violence.",
    "outcome": "Tenochtitlan fell in 1521. Indigenous peoples survived and adapted, despite recurring epidemics and the destruction of political institutions.",
    "nuance": "Disease was one part of conquest, not a complete explanation. Indigenous peoples and cultures did not disappear.",
    "source": "https://www.ncbi.nlm.nih.gov/books/NBK525302/table/pt5.ch17.sec3.table1/",
    "source2": "https://en.wikipedia.org/wiki/Spanish_conquest_of_the_Aztec_Empire"
  },
  {
    "id": "third-plague",
    "year": "1855–1960",
    "location": "CHINA · INDIA · GLOBAL PORT NETWORKS",
    "category": "Pandemic",
    "scope": "International catastrophe",
    "title": "Third plague pandemic",
    "deck": "A new plague pandemic spread from China through shipping networks, with devastating losses in India.",
    "what": "Outbreaks moved through port cities as commerce connected distant populations. Millions died, with the heaviest recorded losses concentrated in Asia.",
    "outcome": "Identifying the bacterium and its transmission helped improve control. Public-health measures and, later, antibiotics reduced the burden.",
    "nuance": "The date range describes a long pandemic era. Plague still exists, and this was never a simultaneous collapse of every society.",
    "source": "https://en.wikipedia.org/wiki/Third_plague_pandemic"
  },
  {
    "id": "volcanic-winter-536",
    "year": "536 CE",
    "location": "NORTHERN HEMISPHERE",
    "category": "Climate shock",
    "scope": "Widespread disruption",
    "title": "Volcanic winter of 536",
    "deck": "A volcanic aerosol veil darkened skies and helped trigger an exceptionally cold period.",
    "what": "Writers described a weakened sun. Tree rings and ice cores support severe cooling; crop failures compounded hardship, and further eruptions extended the climatic disturbance.",
    "outcome": "Communities endured years of disruption. The later Justinianic plague added another crisis, although the effects varied greatly between regions.",
    "nuance": "The source volcano or volcanoes remain debated. The label 'worst year ever' is a modern interpretation, not an objective historical ranking.",
    "source": "https://en.wikipedia.org/wiki/Volcanic_winter_of_536"
  },
  {
    "id": "tambora",
    "year": "1815–1816",
    "location": "SUMBAWA · INDONESIA · NORTHERN HEMISPHERE",
    "category": "Climate shock",
    "scope": "Global climate effects",
    "title": "Mount Tambora eruption",
    "deck": "Tambora's enormous eruption devastated nearby communities and disrupted weather far beyond Indonesia.",
    "what": "Sulfur aerosols cooled the atmosphere. In 1816, unusual cold and rain damaged harvests across parts of Europe and North America, contributing to hunger and unrest.",
    "outcome": "As the volcanic aerosols dispersed, the climate effects weakened. Recovery came unevenly to communities that had lost food, homes, and livelihoods.",
    "nuance": "The 'Year Without a Summer' was not equally severe everywhere. Humanity as a whole was not near extinction.",
    "source": "https://en.wikipedia.org/wiki/1815_eruption_of_Mount_Tambora"
  },
  {
    "id": "krakatoa",
    "year": "August 1883",
    "location": "SUNDA STRAIT · INDONESIA",
    "category": "Volcanic disaster",
    "scope": "Regional catastrophe",
    "title": "Krakatoa eruption",
    "deck": "Krakatoa's violent eruption unleashed tsunamis that destroyed coastal settlements.",
    "what": "Explosions and volcanic collapse drove lethal waves through the Sunda Strait. Tens of thousands died, while atmospheric effects and vivid skies were observed around the world.",
    "outcome": "Coastal communities rebuilt after catastrophic losses. A new volcanic island, Anak Krakatau, later emerged within the caldera.",
    "nuance": "A regional disaster with worldwide atmospheric effects. It did not threaten global civilization with collapse.",
    "source": "https://en.wikipedia.org/wiki/1883_eruption_of_Krakatoa"
  },
  {
    "id": "laki",
    "year": "1783–1784",
    "location": "ICELAND · EUROPE",
    "category": "Volcanic disaster",
    "scope": "Regional catastrophe",
    "title": "Laki eruption",
    "deck": "Iceland's Laki fissures released gases that devastated livestock and food supplies.",
    "what": "Contaminated grazing land killed animals on which people depended. Famine followed, taking around a fifth of Iceland's population; a volcanic haze spread across Europe.",
    "outcome": "The eruptions ended in 1784, but recovery from the livestock and human losses took much longer.",
    "nuance": "Iceland's devastation is well established. Some claimed links to distant famines and political events remain uncertain.",
    "source": "https://en.wikipedia.org/wiki/Laki"
  },
  {
    "id": "toba",
    "year": "~74,000 years ago",
    "location": "SUMATRA · INDONESIA",
    "category": "Disputed near-extinction",
    "scope": "Hypothesis contested",
    "title": "Toba supereruption",
    "deck": "Toba produced a colossal eruption. Whether it nearly wiped out humans is another question.",
    "what": "A popular hypothesis connects volcanic cooling to a severe human population bottleneck. Archaeological evidence from Africa and India, however, shows continuity of human activity across the eruption.",
    "outcome": "Human populations survived. Research suggests that environmental impacts differed between regions and that some areas provided shelter from severe cooling.",
    "nuance": "Not an established near-extinction event. This entry explains why the famous claim should be treated cautiously.",
    "source": "https://pmc.ncbi.nlm.nih.gov/articles/PMC8307270/"
  },
  {
    "id": "bronze-age",
    "year": "~1200 BCE",
    "location": "EASTERN MEDITERRANEAN · NEAR EAST",
    "category": "Societal collapse",
    "scope": "Regional systems crisis",
    "title": "Late Bronze Age collapse",
    "deck": "Palace centers fell, kingdoms fractured, and trade networks unraveled across the eastern Mediterranean.",
    "what": "The Hittite state and Mycenaean palace systems were among those that collapsed. Warfare, migration, drought, and internal instability likely interacted, rather than one cause explaining everything.",
    "outcome": "Some states survived in reduced form; new political and economic networks emerged over generations.",
    "nuance": "The collapse was uneven and unfolded over time. It did not erase all societies or knowledge across the world.",
    "source": "https://en.wikipedia.org/wiki/Late_Bronze_Age_collapse"
  },
  {
    "id": "western-rome",
    "year": "476 CE",
    "location": "WESTERN EUROPE · MEDITERRANEAN",
    "category": "Imperial collapse",
    "scope": "Regional transformation",
    "title": "Fall of the Western Roman Empire",
    "deck": "The removal of Romulus Augustulus became a symbol of the Western Roman Empire's long disintegration.",
    "what": "Civil wars, military pressures, lost territories, and fiscal weakness had eroded imperial authority. In 476, Odoacer deposed the young emperor in Italy.",
    "outcome": "Successor kingdoms governed the West, while the Eastern Roman Empire continued. Roman institutions and culture survived in changing forms.",
    "nuance": "476 is a conventional milestone, not the day civilization stopped. Experiences of decline and continuity differed by region.",
    "source": "https://en.wikipedia.org/wiki/Fall_of_the_Western_Roman_Empire"
  },
  {
    "id": "maya",
    "year": "~750–950 CE",
    "location": "SOUTHERN MAYA LOWLANDS · MESOAMERICA",
    "category": "Societal collapse",
    "scope": "Regional transformation",
    "title": "Classic Maya collapse",
    "deck": "Many great Classic Maya cities lost population and political power over several generations.",
    "what": "Drought, conflict, and strains on food and political systems contributed to the breakdown of numerous southern lowland kingdoms. The timing and causes varied between cities.",
    "outcome": "People moved and communities reorganized. Other Maya centers continued or flourished, and Maya peoples and languages endure.",
    "nuance": "The collapse of particular states was not the disappearance of the Maya or a collapse of all Mesoamerica.",
    "source": "https://en.wikipedia.org/wiki/Classic_Maya_collapse"
  },
  {
    "id": "angkor",
    "year": "14th–15th centuries",
    "location": "ANGKOR · CAMBODIA",
    "category": "Societal crisis",
    "scope": "Regional transformation",
    "title": "Angkor",
    "deck": "Angkor's vast urban network faced a changing climate and shifting political power.",
    "what": "Severe droughts and heavy monsoon episodes stressed water infrastructure. Warfare and economic changes also contributed to the decline of the imperial capital.",
    "outcome": "Political power shifted southward. Angkor's urban population declined, but religious life and Khmer society continued.",
    "nuance": "Angkor was not suddenly abandoned in its entirety. Climate is one part of a complex historical explanation.",
    "source": "https://en.wikipedia.org/wiki/Angkor"
  },
  {
    "id": "great-famine",
    "year": "1315–1317",
    "location": "NORTHERN EUROPE",
    "category": "Famine",
    "scope": "Regional catastrophe",
    "title": "Great Famine of northern Europe",
    "deck": "Years of wet weather exposed how close many medieval communities lived to hunger.",
    "what": "Crops failed, grain prices rose, and exhausted food reserves left people vulnerable. Livestock disease and malnutrition deepened the crisis beyond the first bad harvest.",
    "outcome": "Harvests eventually improved, but recovery was slow and uneven. The famine left lasting damage before plague arrived a generation later.",
    "nuance": "This was a northern European catastrophe. It did not affect every part of Europe or the world equally.",
    "source": "https://en.wikipedia.org/wiki/Great_Famine_of_1315%E2%80%931317"
  },
  {
    "id": "thirty-years-war",
    "year": "1618–1648",
    "location": "CENTRAL EUROPE",
    "category": "War & social breakdown",
    "scope": "Regional catastrophe",
    "title": "Thirty Years’ War",
    "deck": "Decades of fighting devastated parts of the Holy Roman Empire.",
    "what": "Armies requisitioned food, destroyed settlements, and carried disease. Hunger and epidemics killed many more people than battlefield violence alone.",
    "outcome": "The Peace of Westphalia ended the main conflict in 1648. Survivors faced years of reconstruction in landscapes marked by depopulation.",
    "nuance": "Losses varied enormously between regions. Central Europe's suffering was not a collapse of humanity as a whole.",
    "source": "https://en.wikipedia.org/wiki/Thirty_Years%27_War"
  },
  {
    "id": "taiping",
    "year": "1850–1864",
    "location": "CHINA · QING EMPIRE",
    "category": "Civil war",
    "scope": "Regional catastrophe",
    "title": "Taiping Rebellion",
    "deck": "The Taiping Rebellion engulfed large parts of China and shattered countless civilian lives.",
    "what": "Rebel and Qing armies fought for cities and agricultural regions. Warfare, famine, and disease combined into one of history's deadliest civil conflicts.",
    "outcome": "Qing forces captured the Taiping capital at Nanjing in 1864. The dynasty survived, severely weakened, while affected regions faced prolonged recovery.",
    "nuance": "Estimates of deaths run into the tens of millions, but the exact toll is deeply uncertain.",
    "source": "https://en.wikipedia.org/wiki/Taiping_Rebellion"
  },
  {
    "id": "bengal",
    "year": "1943",
    "location": "BENGAL · BRITISH INDIA",
    "category": "Famine",
    "scope": "Regional catastrophe",
    "title": "Bengal famine",
    "deck": "War, market disruption, and failures of policy and relief converged into a devastating famine.",
    "what": "Rice prices rose far beyond many people's means. Lost imports, wartime priorities, crop damage, and inadequate responses helped turn vulnerability into mass hunger and disease.",
    "outcome": "Relief and a better harvest eased the food crisis, but disease continued to kill. Estimates commonly place famine-related deaths at roughly two to three million.",
    "nuance": "Historians debate the weight of individual causes. Colonial governance and people's ability to obtain food are central to understanding the disaster.",
    "source": "https://en.wikipedia.org/wiki/Bengal_famine_of_1943"
  },
  {
    "id": "china-floods",
    "year": "1931",
    "location": "YANGTZE & HUAI RIVER BASINS · CHINA",
    "category": "Flood & famine",
    "scope": "Regional catastrophe",
    "title": "China floods",
    "deck": "Vast floods displaced millions and destroyed the foundations of everyday survival.",
    "what": "Extreme rainfall and swollen rivers inundated settlements and farmland. Drowning was only the beginning: hunger and infectious disease followed displacement.",
    "outcome": "Relief efforts helped some survivors, but damaged crops, housing, and infrastructure extended the emergency long after the waters rose.",
    "nuance": "Death estimates vary greatly depending on whether later disease and famine are included. A precise single figure would be misleading.",
    "source": "https://en.wikipedia.org/wiki/1931_China_floods"
  },
  {
    "id": "world-war-ii",
    "year": "1939–1945",
    "location": "WORLDWIDE",
    "category": "World war",
    "scope": "Global catastrophe",
    "title": "Second World War",
    "deck": "Industrial warfare, genocide, famine, and occupation killed tens of millions.",
    "what": "States mobilized enormous resources for destruction. The Holocaust and other mass atrocities targeted civilians, while cities and food systems were devastated across multiple continents.",
    "outcome": "The Axis powers were defeated in 1945. Reconstruction followed, but the atomic bombings had opened a new era in which future wars could be even more destructive.",
    "nuance": "A global catastrophe with immense regional devastation, not evidence that the human species was on the verge of extinction.",
    "source": "https://en.wikipedia.org/wiki/World_War_II"
  },
  {
    "id": "world-war-one",
    "year": "1914–1918",
    "location": "Europe and a worldwide network of fronts and empires",
    "category": "War",
    "scope": "Global conflict",
    "title": "First World War",
    "deck": "World War I drew more than 30 nations into industrial warfare.",
    "what": "Mass armies, artillery and trench warfare turned a European crisis into a global conflict. More than 65 million people served; civilians faced occupation, shortages and displacement.",
    "outcome": "The November 1918 armistice ended fighting on the Western Front. Millions were dead or wounded, and fighting elsewhere did not simply stop with the armistice.",
    "nuance": "A global human catastrophe, not a near-extinction event. Death estimates vary with the populations and causes included.",
    "source": "https://www.iwm.org.uk/history/first-world-war"
  },
  {
    "id": "dust-bowl",
    "year": "1930s",
    "location": "Great Plains, North America",
    "category": "Environment",
    "scope": "Regional catastrophe",
    "title": "Dust Bowl",
    "deck": "Drought and damaged grasslands turned farmland into airborne dust.",
    "what": "Severe drought struck the Great Plains after plowing and overgrazing had removed much of the vegetation that held its soil. Wind carried exposed topsoil across farms and beyond the region.",
    "outcome": "Farm failures and displacement compounded the Great Depression. Families migrated in search of work while soil conservation became a central public concern.",
    "nuance": "A regional ecological and economic catastrophe. Drought alone does not explain its severity; land use and poverty also mattered.",
    "source": "https://www.loc.gov/classroom-materials/united-states-history-primary-source-timeline/great-depression-and-world-war-ii-1929-1945/dust-bowl/"
  },
  {
    "id": "great-depression",
    "year": "1929–1930s",
    "location": "United States and the world economy",
    "category": "Economic crisis",
    "scope": "Global economic crisis",
    "title": "Great Depression",
    "deck": "A financial collapse became a prolonged crisis of work, food and security.",
    "what": "The downturn that began in 1929 deepened through bank failures and international financial crises. Production collapsed, unemployment surged and the contraction spread around the world.",
    "outcome": "Recovery brought major financial reforms but was uneven and interrupted. In the United States, full output and employment returned during World War II.",
    "nuance": "The Depression was not a single stock-market crash, and its duration differed by country. It was a global social and economic disaster, not a threat of human extinction.",
    "source": "https://www.federalreservehistory.org/essays/great-depression"
  },
  {
    "id": "bhola-cyclone",
    "year": "1970",
    "location": "East Pakistan, now Bangladesh",
    "category": "Storm",
    "scope": "Regional catastrophe",
    "title": "Bhola cyclone",
    "deck": "The Bhola cyclone drove a lethal storm surge over low-lying islands.",
    "what": "On 12–13 November, a cyclone struck the Bay of Bengal coast. Its storm surge overwhelmed islands and tidal flats where many people lived close to sea level.",
    "outcome": "An estimated 300,000–500,000 people died, mostly in the surge. The World Meteorological Organization identifies Bhola as the deadliest tropical cyclone on record.",
    "nuance": "A devastating regional catastrophe. The death toll is an estimate with a wide range, not a precise census.",
    "source": "https://wmo.int/media/news/worlds-deadliest-tropical-cyclone-was-50-years-ago"
  },
  {
    "id": "indian-ocean-tsunami",
    "year": "2004",
    "location": "Indian Ocean coasts",
    "category": "Earthquake & tsunami",
    "scope": "Ocean-basin catastrophe",
    "title": "Indian Ocean tsunami",
    "deck": "A great earthquake sent destructive waves across the Indian Ocean.",
    "what": "On 26 December, a magnitude 9.1 earthquake off northern Sumatra generated a tsunami. Waves devastated coastal communities across the basin, including Indonesia, Sri Lanka, India and Thailand.",
    "outcome": "About 228,000 people were dead or missing. The disaster prompted the development of an Indian Ocean tsunami warning and mitigation system.",
    "nuance": "An international coastal catastrophe, not a global extinction threat. The exact death toll remains uncertain, and impacts varied sharply from coast to coast.",
    "source": "https://vlab.noaa.gov/web/nws-heritage/-/the-banda-aceh-tsunami-of-2004-a-wake-up-call"
  },
  {
    "id": "chernobyl",
    "year": "1986",
    "location": "Ukrainian SSR, Soviet Union; fallout across Europe",
    "category": "Nuclear accident",
    "scope": "Regional disaster with transboundary fallout",
    "title": "Chernobyl",
    "deck": "The Chernobyl reactor disaster spread radioactive contamination beyond national borders.",
    "what": "On 26 April, the accident at reactor 4 exposed workers to intense radiation and contaminated inhabited areas, particularly in Ukraine, Belarus and Russia.",
    "outcome": "Acute radiation sickness killed 28 affected workers within three months. Resettlement, food restrictions and increased thyroid cancer among people exposed when young left a lasting human cost.",
    "nuance": "Observed early deaths and estimates of eventual radiation-related deaths are different measures. Long-term totals are uncertain; this was not a near-extinction event.",
    "source": "https://www.unscear.org/unscear/en/areas-of-work/chernobyl.html"
  },
  {
    "id": "fukushima",
    "year": "2011",
    "location": "Fukushima Prefecture, Japan",
    "category": "Nuclear accident",
    "scope": "Regional catastrophe",
    "title": "Fukushima Daiichi",
    "deck": "An earthquake and tsunami triggered a cascading nuclear emergency.",
    "what": "On 11 March, the tsunami inundated Fukushima Daiichi and disabled vital power and cooling. Three reactor cores were severely damaged, with radioactive releases and evacuations.",
    "outcome": "The accident disrupted communities and livelihoods. UNSCEAR's 2020/2021 assessment found no documented adverse health effects among residents directly attributable to its radiation exposure.",
    "nuance": "The earthquake and tsunami's deaths must not be presented as radiation deaths. Evacuation and social disruption caused serious harm; detectable future radiation-related effects are considered unlikely by UNSCEAR.",
    "source": "https://www.unscear.org/unscear/en/areas-of-work/fukushima-report-faq.html"
  },
  {
    "id": "carrington-event",
    "year": "1859",
    "location": "Earth's magnetosphere; telegraph networks worldwide",
    "category": "Space weather",
    "scope": "Global geophysical event",
    "title": "Carrington Event",
    "deck": "An exceptional geomagnetic storm revealed the vulnerability of wired communication.",
    "what": "In early September, intense solar activity disturbed Earth's magnetic environment. Auroras appeared unusually far south, and induced currents disrupted telegraph networks.",
    "outcome": "Operators reported sparks and electric shocks. Carrington's observation of a bright solar flare became a landmark in the history of space-weather science.",
    "nuance": "This was a major technological disruption, not a documented near-extinction event. Claims about what a similar storm would do today depend on modern infrastructure and uncertain assumptions.",
    "source": "https://apod.nasa.gov/apod/ap160830.html"
  },
  {
    "id": "lisbon-earthquake",
    "year": "1755",
    "location": "Lisbon, Portugal, and Atlantic coasts",
    "category": "Earthquake & tsunami",
    "scope": "Regional catastrophe with transatlantic waves",
    "title": "Lisbon earthquake",
    "deck": "Lisbon faced an earthquake, spreading fires and a tsunami in a single morning.",
    "what": "On 1 November, a great offshore earthquake shattered Lisbon. Fires spread through its ruins; about an hour later, tsunami waves entered the Tagus estuary and struck the waterfront.",
    "outcome": "Tens of thousands died. The tsunami affected Atlantic shores far beyond Portugal, including North Africa and the Caribbean.",
    "nuance": "Historical casualty estimates vary widely, and earthquake magnitude is reconstructed rather than instrumentally measured. This was a regional catastrophe, not the end of the world.",
    "source": "https://sos.noaa.gov/catalog/datasets/tsunami-historical-series-lisbon-1755/"
  },
  {
    "id": "irish-great-famine",
    "year": "1845–1852",
    "location": "Ireland",
    "category": "Famine",
    "scope": "Regional catastrophe with a global diaspora",
    "title": "Great Famine of Ireland",
    "deck": "Repeated potato failures met poverty and inadequate relief in Ireland.",
    "what": "Potato blight devastated a crop on which many impoverished households depended. Insufficient alternative food supplies and relief turned harvest failure into mass hunger and disease.",
    "outcome": "About one million people died and more than a million emigrated. The losses transformed communities and helped shape a far-reaching Irish diaspora.",
    "nuance": "A regional human catastrophe, not a worldwide food collapse. Blight was the trigger; unequal access to food and the response to distress shaped its toll. Population estimates vary.",
    "source": "https://cms.museum.ie/en-IE/Museums/Decorative-Arts-History/Exhibitions/An-Gorta-Mor"
  },
  {
    "id": "thule-radar-1960",
    "year": "1960",
    "location": "Thule, Greenland",
    "category": "Nuclear",
    "scope": "False warning",
    "title": "Thule radar false alarm",
    "deck": "A new warning radar mistook echoes from the rising Moon for incoming missiles.",
    "what": "On 5 October, the Thule early-warning system reported what appeared to be a large Soviet missile attack. The warning reached the North American air-defense network.",
    "outcome": "Officers questioned the report, and the apparent attack was identified as a radar error. No nuclear retaliation followed.",
    "nuance": "A dangerous false warning inside a nuclear command system; it is not evidence that a launch order was issued.",
    "source": "https://blog.ucs.org/david-wright/the-moon-and-nuclear-war-904/"
  },
  {
    "id": "u2-incursion-1962",
    "year": "1962",
    "location": "Chukotka and Alaska",
    "category": "Nuclear",
    "scope": "Escalation risk",
    "title": "U-2 incursion into Soviet airspace",
    "deck": "A U-2 navigation error carried an American aircraft into Soviet airspace during the Cuban Missile Crisis.",
    "what": "On 27 October, Charles Maultsby became disoriented during an Arctic sampling flight and crossed into Soviet territory. Soviet interceptors and American fighters were scrambled.",
    "outcome": "Maultsby returned to Alaska without a clash. The incident added another opportunity for misinterpretation during an already acute superpower crisis.",
    "nuance": "This was a separate incident from the U-2 shot down over Cuba that day; nuclear war did not follow automatically from the overflight.",
    "source": "https://www.vanityfair.com/news/2008/06/missile_crisis_excerpt200806"
  },
  {
    "id": "palomares-1966",
    "year": "1966",
    "location": "Palomares, Spain",
    "category": "Nuclear",
    "scope": "Local contamination",
    "title": "Palomares nuclear accident",
    "deck": "A collision during aerial refueling dropped four nuclear weapons onto land and sea.",
    "what": "On 17 January, a B-52 and KC-135 collided above southern Spain. Conventional explosives in two weapons dispersed radioactive material around Palomares.",
    "outcome": "Seven aircrew died; there was no nuclear detonation. Recovery crews retrieved the weapons, including one from the Mediterranean, and removed contaminated material.",
    "nuance": "A lethal aviation accident and lasting local contamination crisis, not an accidental nuclear explosion or global near-extinction event.",
    "source": "https://www.airforcemedicine.af.mil/Media-Center/Fact-Sheets/Article/2972670/palomares/"
  },
  {
    "id": "thule-crash-1968",
    "year": "1968",
    "location": "Bylot Sound, Greenland",
    "category": "Nuclear",
    "scope": "Local contamination",
    "title": "Thule B-52 crash",
    "deck": "A burning B-52 carrying four nuclear weapons crashed near Thule Air Base.",
    "what": "On 21 January, a cabin fire forced the crew to abandon the bomber. The aircraft struck sea ice, breaking up its nuclear weapons and spreading radioactive contamination.",
    "outcome": "One crew member died; the weapons produced no nuclear yield. A major recovery and cleanup operation followed.",
    "nuance": "The danger was local radioactive contamination and weapons handling failure, not a thermonuclear blast.",
    "source": "https://www.safety.af.mil/News/Article-Display/Article/3342051/not-your-grandfathers-nukes/"
  },
  {
    "id": "goldsboro-1961",
    "year": "1961",
    "location": "North Carolina, United States",
    "category": "Nuclear",
    "scope": "Accidental detonation risk",
    "title": "Goldsboro nuclear accident",
    "deck": "Two thermonuclear weapons fell from a disintegrating bomber near Goldsboro.",
    "what": "On 24 January, a B-52 broke apart over North Carolina. One bomb passed through several stages normally associated with arming as it descended.",
    "outcome": "Neither bomb detonated. Sandia analyses identified the safe position of an electrical switch as crucial to preventing a nuclear yield in one weapon.",
    "nuance": "A potential regional catastrophe from a single accidental explosion; accounts differ in emphasis, so the surviving switch should not be turned into a precise countdown to disaster.",
    "source": "https://nsarchive2.gwu.edu/nukevault/ebb475/"
  },
  {
    "id": "solar-warning-1967",
    "year": "1967",
    "location": "Northern Hemisphere warning stations",
    "category": "Nuclear",
    "scope": "False warning",
    "title": "Solar storm warning-system disruption",
    "deck": "An intense solar radio burst disrupted American missile-warning radars during the Cold War.",
    "what": "On 23 May, solar activity interfered with radar sites in the far north. Military personnel initially considered hostile jamming, a possible precursor to attack.",
    "outcome": "Space-weather forecasters identified the solar cause and helped halt preparations for a military response. The episode strengthened the case for operational solar monitoring.",
    "nuance": "The documented danger was misinterpretation and escalation; evidence does not establish that a nuclear launch order reached the brink of execution.",
    "source": "https://agupubs.onlinelibrary.wiley.com/doi/full/10.1002/2016SW001423"
  },
  {
    "id": "yom-kippur-1973",
    "year": "1973",
    "location": "Sinai and Golan Heights",
    "category": "War",
    "scope": "Regional war; global risk",
    "title": "Yom Kippur War",
    "deck": "The October war brought a regional battlefield and superpower nuclear signaling dangerously close.",
    "what": "Egypt and Syria attacked Israeli forces on 6 October. As the fighting evolved, the United States and Soviet Union supplied opposing sides and confronted the possibility of direct intervention.",
    "outcome": "A ceasefire ended the main fighting after heavy losses. A U.S. worldwide alert during the final diplomatic crisis was followed by de-escalation and disengagement talks.",
    "nuance": "The war was a regional catastrophe with wider nuclear escalation risks, not a nuclear exchange.",
    "source": "https://history.state.gov/milestones/1969-1976/arab-israeli-war-1973"
  },
  {
    "id": "suez-1956",
    "year": "1956",
    "location": "Egypt and the eastern Mediterranean",
    "category": "War",
    "scope": "International crisis",
    "title": "Suez Crisis",
    "deck": "The invasion of Egypt turned a canal dispute into a confrontation among major powers.",
    "what": "After Egypt nationalized the Suez Canal Company, Israel invaded Sinai in October. Britain and France then intervened militarily under a prearranged plan.",
    "outcome": "International pressure, including opposition from the United States, forced a ceasefire and withdrawal. The canal remained under Egyptian control.",
    "nuance": "A destructive regional war with superpower threats and global diplomatic consequences; claims that nuclear war was inevitable overstate the evidence.",
    "source": "https://history.state.gov/milestones/1953-1960/suez"
  },
  {
    "id": "berlin-blockade-1948",
    "year": "1948–1949",
    "location": "Berlin, Germany",
    "category": "War",
    "scope": "Superpower confrontation",
    "title": "Berlin Blockade",
    "deck": "A Soviet blockade placed West Berlin’s survival and Allied resolve under pressure.",
    "what": "In June 1948, the Soviet Union cut surface access to the Western sectors of Berlin. The United States and Britain organized an airlift of food, fuel and other supplies.",
    "outcome": "The blockade was lifted in May 1949. The airlift had sustained the city while avoiding a direct military attempt to break through on the ground.",
    "nuance": "A major Cold War crisis affecting millions, but not an actual nuclear exchange or a verified last-second nuclear launch decision.",
    "source": "https://history.state.gov/milestones/1945-1952/berlin-airlift"
  },
  {
    "id": "taiwan-strait-1958",
    "year": "1958",
    "location": "Kinmen, Matsu and Taiwan Strait",
    "category": "Nuclear",
    "scope": "Escalation risk",
    "title": "Second Taiwan Strait Crisis",
    "deck": "Bombardment of offshore islands tested American commitments to Taiwan.",
    "what": "Chinese forces shelled Nationalist-held islands beginning in August. The United States supplied and escorted Taiwan’s forces while military planners considered options that included nuclear weapons.",
    "outcome": "The crisis eased through diplomacy and a reduction in bombardment. Nuclear weapons were not used.",
    "nuance": "A regional confrontation with serious escalation potential; contingency planning is not the same as an approved nuclear strike.",
    "source": "https://history.state.gov/milestones/1953-1960/taiwan-strait-crises"
  },
  {
    "id": "sino-soviet-1969",
    "year": "1969",
    "location": "Sino-Soviet border",
    "category": "Nuclear",
    "scope": "Escalation risk",
    "title": "Sino-Soviet border conflict",
    "deck": "Fighting along the Soviet–Chinese border raised fears of a much wider war.",
    "what": "Clashes on disputed frontier territory, including Zhenbao/Damansky Island, intensified the split between Moscow and Beijing. U.S. intelligence considered the possibility of Soviet attacks on Chinese nuclear facilities.",
    "outcome": "Diplomatic contact and border talks helped contain the confrontation. No attack on China’s nuclear facilities or nuclear exchange occurred.",
    "nuance": "A dangerous confrontation between nuclear powers; contemporary speculation about attack must be distinguished from a confirmed decision to strike.",
    "source": "https://nsarchive2.gwu.edu/NSAEBB/NSAEBB49/"
  },
  {
    "id": "india-pakistan-2001",
    "year": "2001–2002",
    "location": "India–Pakistan border and Kashmir",
    "category": "Nuclear",
    "scope": "Regional nuclear risk",
    "title": "India–Pakistan military standoff",
    "deck": "An attack on India’s Parliament triggered a long confrontation between nuclear-armed neighbors.",
    "what": "Following the December 2001 attack, India mobilized large forces and Pakistan responded. A further attack in May 2002 renewed fears that the standoff would become war.",
    "outcome": "Diplomatic pressure and eventual troop withdrawals reduced the immediate crisis. The confrontation stopped short of full-scale war.",
    "nuance": "Nuclear weapons heightened the stakes, but the public record does not support a precise claim about how close either side came to using them.",
    "source": "https://www.stimson.org/2008/brink-indian-decision-making-and-2001-2002-standoff-1/"
  },
  {
    "id": "castle-bravo-1954",
    "year": "1954",
    "location": "Bikini Atoll and the Marshall Islands",
    "category": "Nuclear",
    "scope": "Regional fallout",
    "title": "Castle Bravo nuclear test",
    "deck": "The Castle Bravo test spread radioactive fallout far beyond the expected danger area.",
    "what": "On 1 March, the United States detonated a thermonuclear device at Bikini Atoll. Its unexpectedly large yield contaminated inhabited atolls and exposed Marshallese communities and fishing crews.",
    "outcome": "Evacuations and medical monitoring followed, alongside long-term displacement and health concerns. The episode intensified worldwide opposition to atmospheric testing.",
    "nuance": "This was an actual regional radiological disaster with international consequences, not a test that nearly ignited the atmosphere or destroyed Earth.",
    "source": "https://marshallislands.llnl.gov/"
  },
  {
    "id": "windscale-1957",
    "year": "1957",
    "location": "Cumbria, United Kingdom",
    "category": "Nuclear",
    "scope": "Regional contamination",
    "title": "Windscale fire",
    "deck": "A fire at Windscale released radioactive material from a military production reactor.",
    "what": "In October, the core of Windscale Pile 1 overheated and caught fire. Radioactive releases, including iodine-131, spread beyond the facility.",
    "outcome": "The fire was extinguished and milk distribution was restricted across a surrounding area. The damaged pile was permanently shut down.",
    "nuance": "A serious radiological accident with regional exposure; it was not a bomb-like nuclear detonation.",
    "source": "https://inis.iaea.org/records/p6zmt-7r156"
  },
  {
    "id": "kyshtym-1957",
    "year": "1957",
    "location": "Mayak, Soviet Union",
    "category": "Nuclear",
    "scope": "Regional contamination",
    "title": "Kyshtym disaster",
    "deck": "An explosion in stored radioactive waste contaminated a wide area of the southern Urals.",
    "what": "On 29 September, a waste-storage tank at the Mayak nuclear complex exploded after a cooling failure. Radioactive material spread across the surrounding region.",
    "outcome": "Communities were evacuated and contaminated territory was restricted. Soviet secrecy delayed public understanding of the accident and its consequences.",
    "nuance": "A major regional contamination event caused by a chemical explosion in waste, not a nuclear weapon detonation.",
    "source": "https://www.ncbi.nlm.nih.gov/books/NBK597572/"
  },
  {
    "id": "three-mile-island-1979",
    "year": "1979",
    "location": "Pennsylvania, United States",
    "category": "Nuclear",
    "scope": "Reactor accident",
    "title": "Three Mile Island accident",
    "deck": "Equipment failures and operator actions escalated a reactor malfunction at Three Mile Island.",
    "what": "On 28 March, loss of coolant and confusion over the reactor’s condition led to a partial meltdown in Unit 2. The emergency created intense concern about releases and evacuation.",
    "outcome": "The reactor was stabilized and a lengthy cleanup followed. The NRC reports that the small radioactive releases produced no detectable health effects in the surrounding population.",
    "nuance": "A severe reactor accident with far-reaching policy effects; its measured off-site consequences were much smaller than public fears during the emergency.",
    "source": "https://www.nrc.gov/regulations-legislation/fact-sheets-brochures/backgrounder-on-the-three-mile-island-accident"
  },
  {
    "id": "bhopal-1984",
    "year": "1984",
    "location": "Bhopal, India",
    "category": "Industry",
    "scope": "Urban catastrophe",
    "title": "Bhopal disaster",
    "deck": "A pesticide factory released a deadly cloud into sleeping neighborhoods.",
    "what": "On the night of 2–3 December, methyl isocyanate escaped from the Union Carbide India Limited plant. Nearby residents suffered severe toxic exposure.",
    "outcome": "Thousands died, and survivors faced lasting illness and disability. The disaster led to decades of disputes over compensation, accountability and contamination.",
    "nuance": "One of the gravest industrial disasters, concentrated in and around Bhopal; varying death estimates should not be collapsed into a falsely precise total.",
    "source": "https://chemm.hhs.gov/practice/case-studies/the-bhopal-methyl-isocyanate-disaster"
  },
  {
    "id": "great-smog-1952",
    "year": "1952",
    "location": "London, United Kingdom",
    "category": "Environment",
    "scope": "Urban catastrophe",
    "title": "Great Smog of London",
    "deck": "Cold, still weather trapped coal smoke over London for five days.",
    "what": "From 5 to 9 December, dense polluted fog engulfed the capital. Smoke and sulfur pollution accumulated near the ground, disrupting transport and damaging lungs.",
    "outcome": "Thousands of excess deaths were associated with the episode. The disaster helped spur the Clean Air Act of 1956.",
    "nuance": "A catastrophic urban pollution event, not a worldwide atmospheric emergency; death estimates differ depending on the period measured.",
    "source": "https://weather.metoffice.gov.uk/learn-about/weather/case-studies/great-smog"
  },
  {
    "id": "seveso-1976",
    "year": "1976",
    "location": "Lombardy, Italy",
    "category": "Industry",
    "scope": "Regional contamination",
    "title": "Seveso disaster",
    "deck": "A runaway chemical reaction released dioxin over communities near Seveso.",
    "what": "On 10 July, an accident at the ICMESA plant released a toxic cloud containing TCDD. Contamination affected homes, soil, vegetation and animals in surrounding towns.",
    "outcome": "Residents were evacuated from the most contaminated zone and a major cleanup followed. The disaster gave its name to European industrial-accident prevention legislation.",
    "nuance": "A local and regional toxic exposure disaster with enduring regulatory consequences, not a global poisoning event.",
    "source": "https://minerva.jrc.ec.europa.eu/en/shorturl/minerva/9_mahb_bulletin_no9_fortheweb_a4"
  },
  {
    "id": "lake-nyos-1986",
    "year": "1986",
    "location": "Northwest Cameroon",
    "category": "Environment",
    "scope": "Local catastrophe",
    "title": "Lake Nyos disaster",
    "deck": "A sudden release of carbon dioxide from Lake Nyos suffocated surrounding communities.",
    "what": "On 21 August, gas accumulated in the lake’s deep water escaped in a catastrophic burst. Dense carbon dioxide flowed into nearby low-lying ground and displaced breathable air.",
    "outcome": "At least 1,700 people died, along with large numbers of livestock. Scientific investigation identified the lake’s dissolved gas as the source of the disaster.",
    "nuance": "A devastating local limnic eruption; evidence did not show a fresh volcanic eruption triggering the event, and there was no global atmospheric threat.",
    "source": "https://pubs.usgs.gov/publication/ofr8797"
  },
  {
    "id": "covid-19",
    "year": "2019–present",
    "location": "Worldwide",
    "category": "Pandemic",
    "scope": "Global pandemic",
    "title": "COVID-19 pandemic",
    "deck": "A new coronavirus disrupted everyday life across the world.",
    "what": "SARS-CoV-2 emerged in late 2019, and WHO characterized COVID-19 as a pandemic in March 2020. Waves of illness placed extraordinary pressure on health systems.",
    "outcome": "Vaccines, treatment and accumulated immunity changed the course of the emergency. WHO ended the international emergency designation in May 2023 while recognizing COVID-19 as an ongoing health issue.",
    "nuance": "The end of the emergency designation did not mean the disease disappeared; long-term illness and unequal burdens continued.",
    "source": "https://www.who.int/news/item/05-05-2023-statement-on-the-fifteenth-meeting-of-the-international-health-regulations-(2005)-emergency-committee-regarding-the-coronavirus-disease-(covid-19)-pandemic"
  },
  {
    "id": "hiv-aids",
    "year": "1981–present",
    "location": "Worldwide",
    "category": "Pandemic",
    "scope": "Global pandemic",
    "title": "HIV/AIDS pandemic",
    "deck": "A decades-long pandemic transformed medicine, activism and the lives of millions.",
    "what": "AIDS was first clinically reported in 1981, although HIV had circulated earlier. The pandemic brought devastating illness, bereavement and discrimination around the world.",
    "outcome": "Antiretroviral treatment greatly reduced deaths where it became accessible. UNAIDS estimates that tens of millions have died from AIDS-related illness since the epidemic began.",
    "nuance": "This remains an ongoing global crisis, with unequal access to prevention and treatment; 1981 marks recognition, not the origin of HIV.",
    "source": "https://www.hiv.gov/hiv-basics/overview/history/hiv-and-aids-timeline"
  },
  {
    "id": "influenza-1957",
    "year": "1957–1958",
    "location": "Worldwide",
    "category": "Pandemic",
    "scope": "Global pandemic",
    "title": "1957 influenza pandemic",
    "deck": "An H2N2 influenza virus spread across a world connected by modern travel.",
    "what": "The 1957–1958 pandemic was caused by a new influenza A H2N2 virus. Outbreaks interrupted schools, workplaces and hospitals across many countries.",
    "outcome": "CDC estimates about 1.1 million deaths worldwide. The pandemic receded, but influenza continued to evolve and circulate.",
    "nuance": "A global public-health disaster, it did not cause worldwide social collapse; mortality estimates remain approximate.",
    "source": "https://archive.cdc.gov/www_cdc_gov/flu/pandemic-resources/1957-1958-pandemic.html"
  },
  {
    "id": "influenza-1968",
    "year": "1968–1970",
    "location": "Worldwide",
    "category": "Pandemic",
    "scope": "Global pandemic",
    "title": "1968 influenza pandemic",
    "deck": "A new H3N2 influenza strain caused another worldwide wave of illness.",
    "what": "The pandemic began in 1968 and spread internationally. Its H3N2 virus combined a new hemagglutinin with the N2 component of the preceding pandemic strain.",
    "outcome": "CDC estimates about one million deaths worldwide, with much of the excess mortality among older people. Descendants of H3N2 became part of seasonal influenza circulation.",
    "nuance": "Its global reach should not obscure uneven timing and severity between countries.",
    "source": "https://archive.cdc.gov/www_cdc_gov/flu/pandemic-resources/1968-pandemic.html"
  },
  {
    "id": "influenza-2009",
    "year": "2009–2010",
    "location": "Worldwide",
    "category": "Pandemic",
    "scope": "Global pandemic",
    "title": "2009 influenza pandemic",
    "deck": "A novel H1N1 virus spread rapidly and prompted a worldwide vaccination response.",
    "what": "A new influenza A H1N1 virus emerged in 2009 and spread around the world. Its age pattern differed from typical seasonal influenza, with many deaths occurring below age 65.",
    "outcome": "CDC estimates 151,700–575,400 deaths worldwide during its first year. The virus subsequently continued as a seasonal influenza strain.",
    "nuance": "The broad death estimate reflects incomplete surveillance, and pandemic describes geographic spread rather than an extinction-level threat.",
    "source": "https://archive.cdc.gov/www_cdc_gov/flu/pandemic-resources/2009-h1n1-pandemic.html"
  },
  {
    "id": "ebola-west-africa",
    "year": "2014–2016",
    "location": "Guinea, Liberia and Sierra Leone",
    "category": "Epidemic",
    "scope": "Regional epidemic with international spread",
    "title": "West Africa Ebola epidemic",
    "deck": "Ebola devastated families and fragile health systems across three neighboring countries.",
    "what": "The epidemic began in Guinea and spread widely in Liberia and Sierra Leone, reaching their capital cities. WHO declared an international public-health emergency in August 2014.",
    "outcome": "WHO records more than 28,600 infections and 11,325 deaths before the outbreak was declared over in June 2016. Survivors and health services faced lasting consequences.",
    "nuance": "Most transmission occurred in West Africa; imported cases and limited spread elsewhere did not become a worldwide pandemic.",
    "source": "https://www.who.int/emergencies/situations/ebola-outbreak-2014-2016-West-Africa"
  },
  {
    "id": "sars-outbreak",
    "year": "2002–2004",
    "location": "China and international outbreak locations",
    "category": "Epidemic",
    "scope": "International outbreak",
    "title": "SARS outbreak",
    "deck": "An unfamiliar respiratory disease exposed how quickly outbreaks could travel by air.",
    "what": "SARS emerged in southern China in late 2002 and spread internationally in 2003. Hospitals and close-contact settings became important sites of transmission.",
    "outcome": "International investigation and public-health measures interrupted the main chains of transmission in July 2003. Sporadic subsequent cases kept the response active into 2004.",
    "nuance": "SARS had international reach but was contained before sustained worldwide transmission; it was caused by SARS-CoV-1, distinct from COVID-19.",
    "source": "https://www.who.int/health-topics/severe-acute-respiratory-syndrome"
  },
  {
    "id": "cholera-first",
    "year": "1817–1824",
    "location": "Bengal, Asia, Middle East and East Africa",
    "category": "Pandemic",
    "scope": "Interregional pandemic",
    "title": "First cholera pandemic",
    "deck": "Cholera spread far beyond its endemic center through trade and travel.",
    "what": "Beginning in Bengal in 1817, a major cholera outbreak moved across South and Southeast Asia and onward toward the Middle East, East Africa and the Mediterranean. Sudden severe illness overwhelmed communities without modern water treatment.",
    "outcome": "The first pandemic subsided by the mid-1820s, but repeated pandemics followed. Incomplete historical records make a precise death toll unreliable.",
    "nuance": "The first pandemic did not reach every continent; later waves carried cholera more broadly into Europe and the Americas.",
    "source": "https://en.wikipedia.org/wiki/1817%E2%80%931824_cholera_pandemic"
  },
  {
    "id": "ansei-edo",
    "year": "1855",
    "location": "Edo, Japan",
    "category": "Earthquake",
    "scope": "Urban catastrophe",
    "title": "Ansei Edo earthquake",
    "deck": "A nighttime earthquake and fires struck one of the world’s largest cities.",
    "what": "On 11 November 1855, a strong earthquake struck Edo, now Tokyo. Collapsing buildings and subsequent fires caused extensive destruction in densely built neighborhoods.",
    "outcome": "Thousands died, and rebuilding reshaped the city’s economy and public discussion of disaster. Contemporary prints documented damage and expressed social criticism.",
    "nuance": "This was a catastrophe centered on Edo; it should be distinguished from the separate Ansei earthquakes of 1854.",
    "source": "https://www.bousai.go.jp/kyoiku/kyokun/kyoukunnokeishou/rep/1855_ansei_edo_jishin/index.html"
  },
  {
    "id": "san-francisco-1906",
    "year": "1906",
    "location": "Northern California, United States",
    "category": "Earthquake",
    "scope": "Regional catastrophe",
    "title": "San Francisco earthquake",
    "deck": "Shaking and a spreading fire turned San Francisco into a city of ruins.",
    "what": "On 18 April 1906, a major San Andreas Fault earthquake struck northern California. Fires burned across San Francisco after the shaking, greatly increasing the destruction.",
    "outcome": "Research cited by USGS estimates more than 3,000 deaths. Hundreds of thousands lost their homes, while the disaster also advanced earthquake science.",
    "nuance": "The earthquake affected a long coastal region, but the most famous devastation was concentrated in San Francisco; it was not a continental collapse.",
    "source": "https://earthquake.usgs.gov/earthquakes/events/1906calif/18april/casualties.php"
  },
  {
    "id": "great-kanto",
    "year": "1923",
    "location": "Tokyo, Yokohama and the Kanto region, Japan",
    "category": "Earthquake",
    "scope": "Regional catastrophe",
    "title": "Great Kanto earthquake",
    "deck": "Earthquake, fire and violence transformed Japan’s capital region.",
    "what": "On 1 September 1923, a major earthquake struck the southern Kanto region. Collapsed buildings and extensive fires devastated Tokyo and Yokohama.",
    "outcome": "The disaster caused immense loss of life and displacement. In its aftermath, false rumors fueled massacres of Korean residents and others, adding human violence to the disaster.",
    "nuance": "Its destruction was regional; accounts must distinguish deaths from natural hazards from deliberate killings during the aftermath.",
    "source": "https://www.ndl.go.jp/modern/e/cha3/description11.html"
  },
  {
    "id": "tangshan",
    "year": "1976",
    "location": "Tangshan, Hebei, China",
    "category": "Earthquake",
    "scope": "Urban and regional catastrophe",
    "title": "Tangshan earthquake",
    "deck": "A sleeping industrial city was devastated in the early hours of the morning.",
    "what": "At 3:42 a.m. on 28 July 1976, a powerful earthquake struck Tangshan in northeastern China. Extensive building collapse left much of the industrial city in ruins.",
    "outcome": "The official death toll was about 240,000, according to USGS. Reconstruction rebuilt the city over subsequent years.",
    "nuance": "One of the deadliest modern earthquakes, it was nevertheless a regional catastrophe; reported death estimates have varied.",
    "source": "https://www.usgs.gov/publications/tangshan-six-years-later"
  },
  {
    "id": "haiti-2010",
    "year": "2010",
    "location": "Port-au-Prince and surrounding Haiti",
    "category": "Earthquake",
    "scope": "National humanitarian catastrophe",
    "title": "Haiti earthquake",
    "deck": "A shallow earthquake devastated Haiti’s capital and overwhelmed essential services.",
    "what": "On 12 January 2010, a magnitude 7.0 earthquake struck near Port-au-Prince. Building failures damaged homes, hospitals and government facilities across the epicentral region.",
    "outcome": "More than a million people were displaced, and rebuilding continued for years. Death estimates vary substantially between official counts and later studies.",
    "nuance": "The destruction was concentrated in Haiti; vulnerability of buildings and institutions greatly shaped the human toll.",
    "source": "https://www.usgs.gov/publications/overview-2010-haiti-earthquake"
  },
  {
    "id": "kashmir-2005",
    "year": "2005",
    "location": "Kashmir and northern Pakistan",
    "category": "Earthquake",
    "scope": "Regional catastrophe",
    "title": "Kashmir earthquake",
    "deck": "Mountain communities faced collapse, landslides and isolation as winter approached.",
    "what": "The magnitude 7.6 earthquake of 8 October 2005 struck the Kashmir region and northern Pakistan. It triggered thousands of landslides around Muzaffarabad and Balakot.",
    "outcome": "Destroyed settlements and blocked mountain routes complicated rescue and shelter efforts. Landslide-dammed rivers created additional hazards after the shaking ended.",
    "nuance": "The greatest devastation was regional and crossed political boundaries; the scale of loss reflected both shaking and vulnerable mountain infrastructure.",
    "source": "https://pubs.usgs.gov/of/2006/1052/"
  },
  {
    "id": "sichuan-2008",
    "year": "2008",
    "location": "Sichuan and neighboring provinces, China",
    "category": "Earthquake",
    "scope": "Regional catastrophe",
    "title": "Sichuan earthquake",
    "deck": "Strong shaking and thousands of landslides devastated the mountains of western China.",
    "what": "On 12 May 2008, the magnitude 7.9 Wenchuan earthquake struck Sichuan. Collapsed buildings, severed roads and landslides caused widespread destruction.",
    "outcome": "Tens of thousands died, and millions were displaced. Landslides blocked rivers, creating lakes that threatened communities downstream.",
    "nuance": "A vast regional disaster, it did not engulf all of China equally; landslides were a major part of the losses.",
    "source": "https://www.usgs.gov/publications/environmental-impact-landslides-caused-12-may-2008-wenchuan-china-earthquake"
  },
  {
    "id": "valdivia-1960",
    "year": "1960",
    "location": "Southern Chile and the Pacific basin",
    "category": "Earthquake and tsunami",
    "scope": "Regional disaster with transoceanic effects",
    "title": "Valdivia earthquake",
    "deck": "The largest instrumentally recorded earthquake sent destructive waves across the Pacific.",
    "what": "On 22 May 1960, a magnitude 9.5 earthquake struck southern Chile. It damaged cities and coastlines and generated a tsunami that crossed the Pacific.",
    "outcome": "The tsunami caused deaths and destruction as far away as Hawaii and Japan. Communities in southern Chile faced both shaking damage and profound coastal changes.",
    "nuance": "The tsunami had ocean-wide reach, but damage was concentrated in exposed coastal locations; magnitude does not mean uniform global destruction.",
    "source": "https://www.ncei.noaa.gov/news/day-1960-chilean-earthquake-and-tsunami"
  },
  {
    "id": "yellow-river-1887",
    "year": "1887",
    "location": "Yellow River floodplain, China",
    "category": "Flooding",
    "scope": "Regional catastrophe",
    "title": "Yellow River flood of 1887",
    "deck": "A swollen river breached its defenses and inundated densely populated farmland.",
    "what": "After heavy rain in September 1887, the Yellow River broke through dikes near Zhengzhou. Floodwater spread across a large area of the surrounding plains.",
    "outcome": "Drowning, ruined crops and subsequent hardship produced one of history’s deadliest flood disasters. Historical death estimates range widely, commonly around one to two million.",
    "nuance": "The toll is an uncertain historical estimate; this was a regional flood and its aftermath, not a worldwide inundation.",
    "source": "https://www.environmentandsociety.org/tools/keywords/great-flood-huang-ho-river"
  },
  {
    "id": "yellow-river-1938",
    "year": "1938–1947",
    "location": "Henan, Anhui and Jiangsu, China",
    "category": "Wartime flooding",
    "scope": "Regional human-made catastrophe",
    "title": "Yellow River flood of 1938",
    "deck": "A river was deliberately unleashed as a weapon, with devastating civilian consequences.",
    "what": "In June 1938, Chinese Nationalist forces breached Yellow River dikes in an effort to obstruct the Japanese advance. The diverted river flooded farmland and settlements far downstream.",
    "outcome": "Hundreds of thousands died and millions were displaced, although exact figures remain disputed. Flooding and disruption continued until the river was returned to its former course in 1947.",
    "nuance": "This was a deliberate wartime intervention with prolonged regional effects, rather than a purely natural flood.",
    "source": "https://disasterhistory.org/yellow-river-flood-1938-47"
  },
  {
    "id": "north-sea-1953",
    "year": "1953",
    "location": "Netherlands, United Kingdom and Belgium",
    "category": "Flooding",
    "scope": "Regional coastal catastrophe",
    "title": "North Sea flood",
    "deck": "A storm surge overwhelmed coastal defenses around the southern North Sea.",
    "what": "On the night of 31 January–1 February 1953, a severe storm and high sea levels inundated low-lying coasts. Dike breaches flooded Dutch settlements and destructive flooding also struck Britain and Belgium.",
    "outcome": "In the Netherlands, 1,836 people died. The disaster helped drive the Delta Works and major changes to coastal protection and warning systems.",
    "nuance": "This was a North Sea coastal disaster; exposed communities suffered very different outcomes according to elevation, defenses and warning.",
    "source": "https://www.rijkswaterstaat.nl/water/waterbeheer/bescherming-tegen-het-water/watersnoodramp-1953"
  },
  {
    "id": "ancash-1970",
    "year": "1970",
    "location": "Ancash and west-central Peru",
    "category": "Earthquake and landslide",
    "scope": "Regional catastrophe",
    "title": "Ancash earthquake",
    "deck": "An earthquake unleashed a mountain avalanche that buried Yungay.",
    "what": "On 31 May 1970, a destructive earthquake struck west-central Peru. Shaking triggered a huge rock, ice and debris avalanche from Huascarán toward the valley below.",
    "outcome": "The avalanche buried Yungay and part of Ranrahirca, killing many thousands. The wider earthquake also destroyed communities across a large region.",
    "nuance": "The avalanche was one especially lethal component of a regional earthquake disaster; it should not be confused with a volcanic eruption.",
    "source": "https://www.usgs.gov/publications/geological-aspects-may-31-1970-peru-earthquake"
  },
  {
    "id": "mount-pelee-1902",
    "year": "1902",
    "location": "Saint-Pierre, Martinique",
    "category": "Volcanic eruption",
    "scope": "Local catastrophe",
    "title": "Mount Pelée eruption",
    "deck": "A volcanic surge destroyed a Caribbean city within minutes.",
    "what": "On 8 May, Mount Pelée sent a fast-moving cloud of hot gas, ash and rock into Saint-Pierre. The eruption overwhelmed a crowded port beneath the volcano.",
    "outcome": "Tens of thousands of people died and much of the city was destroyed. The catastrophe became a defining example of the danger of pyroclastic surges.",
    "nuance": "The destruction was concentrated in northern Martinique; it was not a worldwide volcanic winter. Popular accounts of a single survivor oversimplify the record.",
    "source": "https://www.usgs.gov/faqs/which-volcanic-eruptions-were-deadliest"
  },
  {
    "id": "nevado-del-ruiz-1985",
    "year": "1985",
    "location": "Armero and surrounding valleys, Colombia",
    "category": "Volcanic eruption",
    "scope": "Regional catastrophe",
    "title": "Nevado del Ruiz eruption",
    "deck": "A comparatively small eruption sent deadly mudflows far beyond the volcano.",
    "what": "On 13 November, hot eruptive material from Nevado del Ruiz melted summit snow and ice. Water mixed with volcanic debris and rushed down river valleys as lahars.",
    "outcome": "The flows buried much of Armero and devastated other settlements, killing more than 23,000 people. Failures to translate warnings into effective evacuation made the losses much worse.",
    "nuance": "The lethal mechanism was a valley-following mudflow, not lava engulfing the country. The disaster shows how a modest eruption can be catastrophic far downstream.",
    "source": "https://www.usgs.gov/observatories/hvo/news/volcano-watch-lessons-learned-armero-colombia-tragedy"
  },
  {
    "id": "pinatubo-1991",
    "year": "1991",
    "location": "Luzon, Philippines",
    "category": "Volcanic eruption",
    "scope": "Regional disaster; global climatic effects",
    "title": "Mount Pinatubo eruption",
    "deck": "Pinatubo devastated nearby communities and temporarily cooled the planet.",
    "what": "The climactic eruption on 15 June sent enormous quantities of ash and sulfur dioxide into the atmosphere. Pyroclastic flows, rain-soaked ash and later lahars devastated areas around the mountain.",
    "outcome": "Forecasting and evacuation saved thousands of lives, although hundreds died and displacement continued. Sulfate aerosols spread around the globe and temporarily lowered average temperatures.",
    "nuance": "The global effect was measurable, short-lived cooling; the direct humanitarian disaster was regional. This was not the end of a climate system or civilization.",
    "source": "https://pubs.usgs.gov/fs/1997/fs113-97/"
  },
  {
    "id": "samalas-1257",
    "year": "1257",
    "location": "Lombok, Indonesia",
    "category": "Volcanic eruption",
    "scope": "Regional devastation; global climatic effects",
    "title": "Samalas eruption",
    "deck": "Samalas collapsed in an immense eruption whose chemical traces reached polar ice.",
    "what": "The eruption spread pumice and pyroclastic material across Lombok and formed the Segara Anak caldera. Its enormous sulfur release entered the stratosphere.",
    "outcome": "The eruption devastated local landscapes and contributed to cooling far beyond Indonesia. Modern researchers connected the volcano with a major sulfate signal preserved in ice cores.",
    "nuance": "The severity of human impacts outside Indonesia varied, and links to particular famines require caution. Evidence supports a major climate disturbance, not universal societal collapse.",
    "source": "https://www.nature.com/articles/srep34868"
  },
  {
    "id": "huaynaputina-1600",
    "year": "1600",
    "location": "Southern Peru",
    "category": "Volcanic eruption",
    "scope": "Regional catastrophe",
    "title": "Huaynaputina eruption",
    "deck": "The Andes' largest historical explosive eruption buried communities and darkened the sky.",
    "what": "Huaynaputina erupted violently in February 1600, spreading ash across southern Peru. Pyroclastic flows and lahars damaged settlements and river valleys.",
    "outcome": "The eruption killed people, buried agricultural land and severely disrupted regional life. Its deposits preserve evidence of one of the most powerful eruptions in South American recorded history.",
    "nuance": "Local devastation is firmly documented; assigning every distant early-seventeenth-century crisis to this eruption would overstate the evidence.",
    "source": "https://volcano.si.edu/volcano.cfm?vn=354030"
  },
  {
    "id": "tenmei-famine",
    "year": "1782–1788",
    "location": "Japan, especially Tōhoku",
    "category": "Famine",
    "scope": "National crisis with regional extremes",
    "title": "Great Tenmei famine",
    "deck": "Repeated harvest failures and the 1783 Asama eruption deepened Japan's Tenmei famine.",
    "what": "Cold, wet weather damaged crops before Mount Asama erupted in 1783. Ashfall aggravated an existing food crisis, while depleted reserves and economic policies increased vulnerability.",
    "outcome": "Starvation, disease and migration devastated communities, especially in northeastern Japan. The famine remained a powerful subject of memory, art and political criticism.",
    "nuance": "The famine lasted several years and had multiple causes; it should not be reduced to one eruption or one bad harvest.",
    "source": "https://www.environmentandsociety.org/arcadia/turning-ash-gold-1783-mount-asama-eruption-and-tenmei-famine-early-modern-japanese-satire"
  },
  {
    "id": "india-famine-1876",
    "year": "1876–1878",
    "location": "British India, especially the south and Deccan",
    "category": "Famine",
    "scope": "Subcontinental catastrophe",
    "title": "Great Famine of India",
    "deck": "Drought became a mass famine in a landscape shaped by poverty and colonial rule.",
    "what": "Severe drought caused harvest failures across southern and western India before the crisis spread northward. High food prices, colonial economic structures and inadequate relief left millions unable to obtain food.",
    "outcome": "Millions died from hunger and associated disease. The disaster exposed how access to food and government decisions could magnify a climatic shock.",
    "nuance": "India's catastrophe was part of a wider period of drought and famine, but conditions and responsibility varied between regions. Exact mortality estimates remain uncertain.",
    "source": "https://en.wikipedia.org/wiki/Great_Famine_of_1876%E2%80%931878"
  },
  {
    "id": "chinese-famine-1959",
    "year": "1959–1961",
    "location": "China",
    "category": "Famine",
    "scope": "National catastrophe",
    "title": "Great Chinese Famine",
    "deck": "An ambitious state campaign produced mass hunger across rural China.",
    "what": "The Great Leap Forward collectivized agriculture and diverted labor while officials exaggerated harvests. Excessive grain procurement and political repression helped turn falling production into widespread starvation.",
    "outcome": "Tens of millions died, although estimates differ. Policy retreat and changes in food procurement eventually helped bring the acute famine to an end.",
    "nuance": "Weather contributed in some areas, but treating the famine as simply a natural disaster obscures the decisive role of state policy.",
    "source": "https://www.bmj.com/content/319/7225/1619"
  },
  {
    "id": "soviet-famine-1932",
    "year": "1932–1933",
    "location": "Ukraine, Kazakhstan and other Soviet regions",
    "category": "Famine",
    "scope": "Multi-regional catastrophe",
    "title": "Soviet famine of 1932–1933",
    "deck": "Forced collectivization and coercive food policies drove catastrophic hunger across Soviet regions.",
    "what": "Stalin's agricultural transformation, requisitions and repression disrupted food production and access. Ukraine, Kazakhstan, the North Caucasus and other regions suffered devastating losses.",
    "outcome": "Millions died and communities were uprooted. In Ukraine, the catastrophe is remembered as the Holodomor, with specific policies targeting and restricting the starving population.",
    "nuance": "The Soviet famines were connected but not identical: Ukraine's Holodomor and the destruction of pastoral livelihoods in Kazakhstan have distinct histories.",
    "source": "https://www.loc.gov/exhibits/archives/intn"
  },
  {
    "id": "russian-famine-1921",
    "year": "1921–1922",
    "location": "Soviet Russia, especially the Volga region",
    "category": "Famine",
    "scope": "Multi-regional catastrophe",
    "title": "Russian famine of 1921–1922",
    "deck": "War, coercive economic policy and drought left millions facing starvation.",
    "what": "Years of world war, revolution and civil war had damaged agriculture and transport. Requisitioning and severe drought compounded the collapse in food supplies.",
    "outcome": "Millions died in the famine and associated disease outbreaks. International relief, including the American Relief Administration, fed large numbers of people.",
    "nuance": "This was a catastrophe across several Soviet territories, not a global shortage of food. Relief crossed political divisions even as distrust persisted.",
    "source": "https://www.hoover.org/events/hoover-book-club-bread-medicine-american-famine-relief-soviet-russia-1921-1923"
  },
  {
    "id": "ethiopian-famine-1983",
    "year": "1983–1985",
    "location": "Ethiopia, especially the north",
    "category": "Famine",
    "scope": "Regional humanitarian catastrophe",
    "title": "Ethiopian famine",
    "deck": "Drought and war combined with destructive government policies to create mass starvation.",
    "what": "Crop failures struck people already exposed to poverty and conflict. Counterinsurgency operations, restrictions on movement and trade, and agricultural policies worsened food insecurity.",
    "outcome": "The famine killed vast numbers and displaced communities, while televised reporting prompted an enormous international relief response. Aid itself became entangled with military and resettlement policies.",
    "nuance": "Calling this only a drought disaster hides the role of war and political decisions. Different Ethiopian regions experienced distinct crises.",
    "source": "https://www.hrw.org/reports/1992/WR92/AFW-02.htm"
  },
  {
    "id": "dutch-hunger-winter",
    "year": "1944–1945",
    "location": "Western Netherlands",
    "category": "Famine",
    "scope": "Regional wartime catastrophe",
    "title": "Dutch Hunger Winter",
    "deck": "Food and fuel ran out in the occupied western Netherlands during the war's final winter.",
    "what": "German restrictions on food transport, disrupted railways and wartime conditions isolated densely populated western areas. Severe winter conditions made obtaining food and fuel still harder.",
    "outcome": "Thousands died and many residents traveled into the countryside seeking food. Allied relief deliveries and liberation in 1945 ended the acute crisis.",
    "nuance": "The famine was concentrated in the western Netherlands; other parts of the country had different wartime experiences. Mortality estimates distinguish direct starvation from wider excess deaths.",
    "source": "https://www.niod.nl/en/search-guide-hunger-winter/"
  },
  {
    "id": "leningrad-siege",
    "year": "1941–1944",
    "location": "Leningrad, Soviet Union",
    "category": "Siege",
    "scope": "Urban catastrophe",
    "title": "Siege of Leningrad",
    "deck": "The blockade of Leningrad turned hunger and winter into weapons against civilians.",
    "what": "German forces cut the city's land connections in September 1941. Bombardment and the blockade produced catastrophic shortages, especially during the first winter.",
    "outcome": "Hundreds of thousands of civilians died while residents maintained parts of the city's industry and defenses. The siege was finally lifted in January 1944.",
    "nuance": "This was a deliberate wartime siege of a city and its surrounding region. Survival routes across Lake Ladoga were vital but could not prevent mass death.",
    "source": "https://www.dhm.de/lemo/kapitel/der-zweite-weltkrieg/kriegsverlauf/belagerung-von-leningrad"
  },
  {
    "id": "baghdad-1258",
    "year": "1258",
    "location": "Baghdad, present-day Iraq",
    "category": "Siege",
    "scope": "Urban catastrophe; imperial rupture",
    "title": "Siege of Baghdad",
    "deck": "Mongol conquest destroyed much of Baghdad and ended Abbasid rule from the city.",
    "what": "Hulagu's forces besieged Baghdad and captured it in February 1258. The sack brought widespread killing and destruction, including the execution of the caliph al-Musta'sim.",
    "outcome": "The Abbasid political center in Baghdad came to an end, and regional power shifted under Mongol rule. The city survived, though profoundly damaged.",
    "nuance": "Medieval casualty figures are highly uncertain. The sack did not end Islamic civilization or scholarship across the wider world.",
    "source": "https://en.wikipedia.org/wiki/Siege_of_Baghdad"
  },
  {
    "id": "rwanda-genocide-1994",
    "year": "1994",
    "location": "Rwanda",
    "category": "Genocide",
    "scope": "National catastrophe",
    "title": "Genocide against the Tutsi in Rwanda",
    "deck": "Extremist leaders organized a genocide against Rwanda's Tutsi population.",
    "what": "From April to July, extremist Hutu leaders, militias and their collaborators directed mass killing of Tutsi civilians. Hutu opponents of the violence were also murdered.",
    "outcome": "Hundreds of thousands were killed and survivors faced profound loss and displacement. The United Nations later established the International Criminal Tribunal for Rwanda.",
    "nuance": "The genocide was an organized campaign, not an inevitable eruption of ancient hatred. Its consequences also spread into neighboring countries.",
    "source": "https://encyclopedia.ushmm.org/content/en/article/the-rwanda-genocide"
  },
  {
    "id": "cambodian-genocide",
    "year": "1975–1979",
    "location": "Cambodia",
    "category": "Genocide",
    "scope": "National catastrophe",
    "title": "Cambodian genocide",
    "deck": "The Khmer Rouge pursued radical social transformation through terror, forced labor and mass killing.",
    "what": "After taking power in April 1975, the Khmer Rouge emptied cities and subjected people to forced labor and persecution. Executions, starvation and disease spread under the regime.",
    "outcome": "Nearly two million people died before Khmer Rouge rule was overthrown in 1979. Survivors carried enduring losses, while later trials addressed crimes committed by senior leaders.",
    "nuance": "The mass atrocities included genocide against targeted ethnic and religious groups as well as crimes against humanity against the wider population.",
    "source": "https://www.ushmm.org/genocide-prevention/countries/cambodia/cambodia-1975"
  },
  {
    "id": "armenian-genocide-1915",
    "year": "1915–1916",
    "location": "Ottoman Empire",
    "category": "Genocide",
    "scope": "Population catastrophe",
    "title": "Armenian genocide",
    "deck": "Ottoman authorities targeted Armenian communities through deportation, killing and lethal deprivation.",
    "what": "Beginning in 1915, arrests, massacres and forced deportations tore Armenian communities apart. Many people died from systematic ill-treatment, starvation, exposure and disease.",
    "outcome": "Hundreds of thousands of Armenians were killed, with estimates exceeding a million in some scholarship. Survivors formed displaced communities and diasporas across the world.",
    "nuance": "The genocide was a targeted human catastrophe within World War I, not merely collateral damage from fighting. Armenian life continued despite the immense destruction.",
    "source": "https://encyclopedia.ushmm.org/content/en/article/the-armenian-genocide-1915-16-overview"
  },
  {
    "id": "tenochtitlan-1521",
    "year": "1521",
    "location": "Tenochtitlan, present-day Mexico City",
    "category": "Conquest",
    "scope": "Urban catastrophe; imperial collapse",
    "title": "Fall of Tenochtitlan",
    "deck": "A Spanish-led coalition and its many Indigenous allies destroyed the Mexica capital.",
    "what": "After warfare and a devastating smallpox epidemic, Tenochtitlan endured a prolonged siege. Cortés's forces and numerous Indigenous allies cut supplies and fought through the city.",
    "outcome": "The capital surrendered on 13 August, ending the Aztec Empire's political power. Tens of thousands died and colonial rule developed over the conquered city and surrounding lands.",
    "nuance": "The conquest depended heavily on Indigenous alliances, not a small Spanish force acting alone. The fall of the state did not mean the disappearance of Indigenous peoples or cultures.",
    "source": "https://origins.osu.edu/milestones/fall-tenochtitlan"
  },
  {
    "id": "galveston-1900",
    "year": "1900",
    "location": "Galveston, Texas, United States",
    "category": "Hurricane",
    "scope": "Local and regional catastrophe",
    "title": "Galveston hurricane",
    "deck": "A hurricane's storm surge overwhelmed the low-lying city of Galveston.",
    "what": "On 8 September, a powerful hurricane struck the Texas coast. Water and wind destroyed thousands of homes on Galveston Island.",
    "outcome": "Thousands died in the deadliest natural disaster in United States history. Survivors rebuilt a city whose vulnerability had been brutally exposed.",
    "nuance": "The devastation was concentrated on the island and nearby coast. Historical death totals are estimates, not an exact census of every loss.",
    "source": "https://vlab.noaa.gov/web/nws-heritage/-/galveston-storm-of-1900"
  },
  {
    "id": "nargis-2008",
    "year": "2008",
    "location": "Ayeyarwady Delta, Myanmar",
    "category": "Cyclone",
    "scope": "Regional catastrophe",
    "title": "Cyclone Nargis",
    "deck": "Cyclone Nargis inundated the delta and shattered coastal communities.",
    "what": "The cyclone struck in early May, pushing storm surge through low-lying settlements and farmland. Homes, crops and local infrastructure were destroyed across the delta.",
    "outcome": "Almost 140,000 people were reported dead or missing. An estimated 2.4 million people lost all or part of their homes, livelihoods or community structures.",
    "nuance": "These figures combine confirmed deaths and missing people. The event was a regional disaster with international humanitarian consequences, not a worldwide flood.",
    "source": "https://myanmar.unfpa.org/en/publications/post-nargis-recovery-and-preparedness-plan-2008"
  }
];
